### PR TITLE
iDRAC 8 bugfix

### PR DESCRIPTION
**Pull request by nferch**
Also fill in some missing Debian changelog

### CODE REVIEW

**Comment by negz** [comment]
LGTM, with the usual I don't know Ruby caveat.

Also, I'm guessing the 0.4.0 changelog update is for a previously merged PR?

**Comment by philipcristiano** [comment]
LGTM, with the @negz's usual "I don't know Ruby caveat".

**Comment by jhuntwork** [comment]
:+1:

**Comment by nferch** [comment]
@dmichel1 in my testing Patron/something in the stack was decompressing the response, but I made the code handle both cases just in case.

**Pull request merged**
